/* Axiovex Systems blog — client behaviors for the statically built blog.
   Pages are generated by scripts/build-site.mjs; this script only wires:
   year, mobile nav, index search/tag filtering, and article share buttons. */
(function () {
  'use strict';

  var year = document.getElementById('year');
  if (year) year.textContent = new Date().getFullYear();

  /* ---------- Mobile nav (same pattern as the main site) ---------- */
  (function initNav() {
    var t = document.querySelector('.nav-toggle');
    var m = document.getElementById('mobile-menu');
    if (!t || !m) return;
    function set(open) {
      m.classList.toggle('open', open);
      t.setAttribute('aria-expanded', open ? 'true' : 'false');
      t.setAttribute('aria-label', open ? 'Close menu' : 'Open menu');
    }
    t.addEventListener('click', function () { set(!m.classList.contains('open')); });
    m.addEventListener('click', function (e) { if (e.target.closest('a')) set(false); });
    document.addEventListener('keydown', function (e) { if (e.key === 'Escape') set(false); });
  })();

  /* ---------- Blog index: search + tag filtering over static cards ---------- */
  (function initIndex() {
    var list = document.getElementById('post-list');
    var search = document.getElementById('blog-search');
    var count = document.getElementById('post-count');
    var empty = document.getElementById('no-results');
    if (!list || !search) return;

    function applyFilter() {
      var q = search.value.trim().toLowerCase();
      var visible = 0;
      Array.prototype.forEach.call(list.children, function (card) {
        var hit = !q || (card.getAttribute('data-search') || '').indexOf(q) !== -1;
        card.style.display = hit ? '' : 'none';
        if (hit) visible++;
      });
      if (empty) empty.style.display = visible ? 'none' : '';
      if (count) {
        count.textContent = visible + (visible === 1 ? ' article' : ' articles') +
          (q ? ' matching \u201c' + search.value.trim() + '\u201d' : '');
      }
    }
    search.addEventListener('input', applyFilter);
    list.addEventListener('click', function (e) {
      var pill = e.target.closest('.tag-pill');
      if (pill) { search.value = pill.getAttribute('data-tag'); applyFilter(); search.focus(); }
    });
    // prefill from ?q= (tag pills on article pages link here)
    var m = /[?&]q=([^&]+)/.exec(location.search);
    if (m) { search.value = decodeURIComponent(m[1]); applyFilter(); }
  })();

  /* ---------- Article share buttons ---------- */
  (function initShare() {
    Array.prototype.forEach.call(document.querySelectorAll('.share-copy'), function (btn) {
      btn.addEventListener('click', function () {
        var url = btn.getAttribute('data-url');
        function done() {
          btn.classList.add('copied');
          var span = btn.querySelector('span');
          if (span) span.textContent = 'Copied!';
          setTimeout(function () {
            btn.classList.remove('copied');
            if (span) span.textContent = 'Copy link';
          }, 2000);
        }
        function fallback() {
          var ta = document.createElement('textarea');
          ta.value = url; document.body.appendChild(ta); ta.select();
          try { document.execCommand('copy'); done(); } catch (e) { /* noop */ }
          document.body.removeChild(ta);
        }
        if (navigator.clipboard && navigator.clipboard.writeText) {
          navigator.clipboard.writeText(url).then(done, fallback);
        } else fallback();
      });
    });
    Array.prototype.forEach.call(document.querySelectorAll('.share-native'), function (btn) {
      if (!navigator.share) { btn.style.display = 'none'; return; }
      btn.addEventListener('click', function () {
        navigator.share({
          title: btn.getAttribute('data-title'),
          text: btn.getAttribute('data-title'),
          url: btn.getAttribute('data-url'),
        }).catch(function () { /* dismissed */ });
      });
    });
  })();
})();
